services:
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: todos
#    env_file:
#      - ./db-variables.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: